#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin_App.Resource", IsApplication=true)]

namespace Xamarin_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060004
			public const int darkblue = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int darkgey = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int darkpink = 2131099655;
			
			// aapt resource value: 0x7f060002
			public const int dgreen = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int purple = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int theme_custom_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int theme_material_light_background = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int yellow = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int cover = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edittext_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_about = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_book = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_book1 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_book2 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_book3 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_book4 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_book5 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_camera = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_camera_back = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_email = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_lock = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_new = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int ic_order = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ic_profile = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int ic_record = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int ic_splach = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int icnew = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Icon = 2130837524;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int button1 = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int button2 = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int editText1 = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int editText2 = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int gridview = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int image1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int imageView1 = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int scrollView1 = 2131165193;
			
			// aapt resource value: 0x7f070004
			public const int textView1 = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int textView2 = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int textView3 = 2131165194;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int buybook = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int buybook_element = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int camera_layout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Dashboard = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int grid_element = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int intro = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int login = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int newbook = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int Theme_Custom_Login = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
